services:
  crawl4ai:
    image: unclecode/crawl4ai:0.7.3
    container_name: robaicrawler
    ports:
      - "${CRAWL4AI_PORT:-11235}:11235"
    shm_size: '${CRAWL4AI_SHM_SIZE:-1gb}'
    restart: ${CRAWL4AI_RESTART_POLICY:-unless-stopped}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11235/"]
      interval: ${CRAWL4AI_HEALTH_INTERVAL:-30s}
      timeout: ${CRAWL4AI_HEALTH_TIMEOUT:-10s}
      retries: ${CRAWL4AI_HEALTH_RETRIES:-3}
    environment:
      - LOG_LEVEL=${CRAWL4AI_LOG_LEVEL:-INFO}
      - CORS_ORIGINS=${CRAWL4AI_CORS_ORIGINS:-*}
